name: Deploy

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to the main branch

permissions:
  contents: write  # Grants write access to the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Add any additional steps you need below
      # For example, a build or deployment step
