name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          cache: bundler

      - name: Install dependencies
      working-directory: ./docs
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
          future: true
          verbose: true
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in token
